# Generated by Django 6.1 on 2026-09-04 09:17

# pyrefly: ignore [missing-import]
from django.db import migrations, models


def fix_otp_table_and_index(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        tables = [t.lower() for t in connection.introspection.table_names(cursor)]

        if 'buddies_otpverification' in tables and 'core_otpverification' not in tables:
            schema_editor.execute("ALTER TABLE `buddies_otpverification` RENAME TO `core_otpverification`")
            tables.append('core_otpverification')
        elif 'buddie_otpverification' in tables and 'core_otpverification' not in tables:
            schema_editor.execute("ALTER TABLE `buddie_otpverification` RENAME TO `core_otpverification`")
            tables.append('core_otpverification')
        elif 'core_otpverification' not in tables:
            OTPVerification = apps.get_model('core', 'OTPVerification')
            schema_editor.create_model(OTPVerification)
            return

        constraints = connection.introspection.get_constraints(cursor, 'core_otpverification')
        OTPVerification = apps.get_model('core', 'OTPVerification')
        new_index = models.Index(fields=['phone_number', 'purpose'], name='core_otpver_phone_n_10ca4e_idx')
        old_index = models.Index(fields=['phone_number', 'purpose'], name='buddie_otpv_phone_n_09d9c8_idx')

        if 'buddie_otpv_phone_n_09d9c8_idx' in constraints and 'core_otpver_phone_n_10ca4e_idx' not in constraints:
            if connection.vendor == 'mysql':
                try:
                    cursor.execute("ALTER TABLE `core_otpverification` RENAME INDEX `buddie_otpv_phone_n_09d9c8_idx` TO `core_otpver_phone_n_10ca4e_idx`")
                except Exception:
                    try:
                        schema_editor.remove_index(OTPVerification, old_index)
                        schema_editor.add_index(OTPVerification, new_index)
                    except Exception:
                        pass
            else:
                try:
                    schema_editor.remove_index(OTPVerification, old_index)
                    schema_editor.add_index(OTPVerification, new_index)
                except Exception:
                    pass
        elif 'core_otpver_phone_n_10ca4e_idx' not in constraints:
            try:
                schema_editor.add_index(OTPVerification, new_index)
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_verified_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_otp_table_and_index, migrations.RunPython.noop),
    ]
