# Generated by Django 6.1 on 2026-09-05 05:49

# pyrefly: ignore [missing-import]
import django.db.models.deletion
# pyrefly: ignore [missing-import]
from django.db import migrations, models


def ensure_tables_and_indexes(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        tables = [t.lower() for t in connection.introspection.table_names(cursor)]

        # 1. Ensure core_buddyprofile exists
        if 'buddies_buddyprofile' in tables and 'core_buddyprofile' not in tables:
            schema_editor.execute("ALTER TABLE `buddies_buddyprofile` RENAME TO `core_buddyprofile`")
            tables.append('core_buddyprofile')
        elif 'buddie_buddyprofile' in tables and 'core_buddyprofile' not in tables:
            schema_editor.execute("ALTER TABLE `buddie_buddyprofile` RENAME TO `core_buddyprofile`")
            tables.append('core_buddyprofile')
        elif 'core_buddyprofile' not in tables:
            try:
                BuddyProfile = apps.get_model('core', 'BuddyProfile')
                schema_editor.create_model(BuddyProfile)
            except Exception:
                schema_editor.execute("""
                    CREATE TABLE IF NOT EXISTS `core_buddyprofile` (
                        `id` integer PRIMARY KEY AUTOINCREMENT,
                        `bio` text NOT NULL,
                        `languages` varchar(200) NOT NULL,
                        `rate_per_minute` integer unsigned NOT NULL,
                        `rating` decimal(3,2) NOT NULL,
                        `total_calls` integer unsigned NOT NULL,
                        `is_online` bool NOT NULL,
                        `is_busy` bool NOT NULL,
                        `is_verified` bool NOT NULL,
                        `profession_id` bigint DEFAULT NULL,
                        `user_id` bigint NOT NULL UNIQUE
                    )
                """ if connection.vendor == 'sqlite' else """
                    CREATE TABLE IF NOT EXISTS `core_buddyprofile` (
                        `id` bigint NOT NULL AUTO_INCREMENT,
                        `bio` longtext NOT NULL,
                        `languages` varchar(200) NOT NULL,
                        `rate_per_minute` int unsigned NOT NULL,
                        `rating` decimal(3,2) NOT NULL,
                        `total_calls` int unsigned NOT NULL,
                        `is_online` tinyint(1) NOT NULL,
                        `is_busy` tinyint(1) NOT NULL,
                        `is_verified` tinyint(1) NOT NULL,
                        `profession_id` bigint DEFAULT NULL,
                        `user_id` bigint NOT NULL,
                        PRIMARY KEY (`id`),
                        UNIQUE KEY `user_id` (`user_id`)
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                """)
            tables.append('core_buddyprofile')

        # 2. Ensure core_profession exists so DeleteModel can drop it cleanly
        if 'buddies_profession' in tables and 'core_profession' not in tables:
            schema_editor.execute("ALTER TABLE `buddies_profession` RENAME TO `core_profession`")
            tables.append('core_profession')
        elif 'buddie_profession' in tables and 'core_profession' not in tables:
            schema_editor.execute("ALTER TABLE `buddie_profession` RENAME TO `core_profession`")
            tables.append('core_profession')
        elif 'core_profession' not in tables:
            try:
                Profession = apps.get_model('core', 'Profession')
                schema_editor.create_model(Profession)
            except Exception:
                schema_editor.execute("""
                    CREATE TABLE IF NOT EXISTS `core_profession` (
                        `id` integer PRIMARY KEY AUTOINCREMENT,
                        `name` varchar(100) NOT NULL,
                        `icon` varchar(100) DEFAULT NULL,
                        `description` text NOT NULL,
                        `is_active` bool NOT NULL,
                        `created_at` datetime NOT NULL
                    )
                """ if connection.vendor == 'sqlite' else """
                    CREATE TABLE IF NOT EXISTS `core_profession` (
                        `id` bigint NOT NULL AUTO_INCREMENT,
                        `name` varchar(100) NOT NULL,
                        `icon` varchar(100) DEFAULT NULL,
                        `description` longtext NOT NULL,
                        `is_active` tinyint(1) NOT NULL,
                        `created_at` datetime(6) NOT NULL,
                        PRIMARY KEY (`id`)
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                """)
            tables.append('core_profession')

        # 3. For OTPVerification index, ensure old index exists so RenameIndex finds it
        if 'core_otpverification' in tables:
            constraints = connection.introspection.get_constraints(cursor, 'core_otpverification')
            if 'buddie_otpv_phone_n_09d9c8_idx' not in constraints and 'core_otpver_phone_n_10ca4e_idx' in constraints:
                if connection.vendor == 'mysql':
                    try:
                        cursor.execute("ALTER TABLE `core_otpverification` RENAME INDEX `core_otpver_phone_n_10ca4e_idx` TO `buddie_otpv_phone_n_09d9c8_idx`")
                    except Exception:
                        pass
                else:
                    try:
                        schema_editor.execute("DROP INDEX IF EXISTS `core_otpver_phone_n_10ca4e_idx`")
                        schema_editor.execute("CREATE INDEX IF NOT EXISTS `buddie_otpv_phone_n_09d9c8_idx` ON `core_otpverification` (`phone_number`, `purpose`)")
                    except Exception:
                        pass
            elif 'buddie_otpv_phone_n_09d9c8_idx' not in constraints and 'core_otpver_phone_n_10ca4e_idx' not in constraints:
                try:
                    schema_editor.execute("CREATE INDEX IF NOT EXISTS `buddie_otpv_phone_n_09d9c8_idx` ON `core_otpverification` (`phone_number`, `purpose`)")
                except Exception:
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_category'),
    ]

    operations = [
        migrations.RunPython(ensure_tables_and_indexes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='buddyprofile',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buddies', to='core.category'),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='core_otpver_phone_n_10ca4e_idx',
            old_name='buddie_otpv_phone_n_09d9c8_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='core_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='core_user_permissions_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
    ]
