# Generated by Django 6.1 on 2026-09-07
# pyrefly: ignore [missing-import]
import django.db.models.deletion
# pyrefly: ignore [missing-import]
from django.db import migrations, models


def ensure_call_columns(apps, schema_editor):
    """
    Safely ensures category_id, accepted_at, and rejected_at columns exist on core_call.
    """
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        tables = [t.lower() for t in connection.introspection.table_names(cursor)]
        if 'core_call' in tables:
            columns = [col.name.lower() for col in connection.introspection.get_table_description(cursor, 'core_call')]
            
            if 'category_id' not in columns:
                if connection.vendor == 'sqlite':
                    schema_editor.execute("ALTER TABLE `core_call` ADD COLUMN `category_id` bigint REFERENCES `core_category` (`id`) DEFERRABLE INITIALLY DEFERRED")
                else:
                    schema_editor.execute("ALTER TABLE `core_call` ADD COLUMN `category_id` bigint DEFAULT NULL")
            
            if 'accepted_at' not in columns:
                schema_editor.execute("ALTER TABLE `core_call` ADD COLUMN `accepted_at` datetime NULL")
                
            if 'rejected_at' not in columns:
                schema_editor.execute("ALTER TABLE `core_call` ADD COLUMN `rejected_at` datetime NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_buddyprofile_profession_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RunPython(ensure_call_columns, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('RINGING', 'Ringing'),
                    ('ACCEPTED', 'Accepted'),
                    ('ACTIVE', 'Active'),
                    ('COMPLETED', 'Completed'),
                    ('REJECTED', 'Rejected'),
                    ('CANCELLED', 'Cancelled'),
                    ('MISSED', 'Missed'),
                    ('ENDED', 'Ended'),
                ],
                default='RINGING',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='call',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='calls',
                to='core.category',
            ),
        ),
        migrations.AddField(
            model_name='call',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
