# Generated by Django 6.1 on 2026-09-07
# pyrefly: ignore [missing-import]
from django.db import migrations, models


def ensure_privacy_columns(apps, schema_editor):
    """
    Safely ensures profile_visible_in_feed and ghost_calling_mode columns
    exist on core_callerprofile.
    """
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        tables = [t.lower() for t in connection.introspection.table_names(cursor)]
        if 'core_callerprofile' in tables:
            columns = [col.name.lower() for col in connection.introspection.get_table_description(cursor, 'core_callerprofile')]

            if 'profile_visible_in_feed' not in columns:
                try:
                    if connection.vendor == 'sqlite':
                        schema_editor.execute("ALTER TABLE `core_callerprofile` ADD COLUMN `profile_visible_in_feed` bool NOT NULL DEFAULT 1")
                    else:
                        schema_editor.execute("ALTER TABLE `core_callerprofile` ADD COLUMN `profile_visible_in_feed` tinyint(1) NOT NULL DEFAULT 1")
                except Exception:
                    pass

            if 'ghost_calling_mode' not in columns:
                try:
                    if connection.vendor == 'sqlite':
                        schema_editor.execute("ALTER TABLE `core_callerprofile` ADD COLUMN `ghost_calling_mode` bool NOT NULL DEFAULT 0")
                    else:
                        schema_editor.execute("ALTER TABLE `core_callerprofile` ADD COLUMN `ghost_calling_mode` tinyint(1) NOT NULL DEFAULT 0")
                except Exception:
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_call_workflow_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_privacy_columns, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='callerprofile',
                    name='profile_visible_in_feed',
                    field=models.BooleanField(default=True),
                ),
                migrations.AddField(
                    model_name='callerprofile',
                    name='ghost_calling_mode',
                    field=models.BooleanField(default=False),
                ),
            ]
        ),
    ]
