# Generated by Django 6.1 on 2026-09-07
# pyrefly: ignore [missing-import]
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def ensure_favorite_table(apps, schema_editor):
    """
    Safely creates the core_callerfavorite table if it does not already exist.
    """
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        tables = [t.lower() for t in connection.introspection.table_names(cursor)]
        if 'core_callerfavorite' not in tables:
            if connection.vendor == 'sqlite':
                schema_editor.execute("""
                    CREATE TABLE `core_callerfavorite` (
                        `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                        `created_at` datetime NOT NULL,
                        `agent_id` bigint NOT NULL REFERENCES `core_user` (`id`) DEFERRABLE INITIALLY DEFERRED,
                        `caller_id` bigint NOT NULL REFERENCES `core_user` (`id`) DEFERRABLE INITIALLY DEFERRED,
                        CONSTRAINT `core_callerfavorite_caller_id_agent_id_uniq` UNIQUE (`caller_id`, `agent_id`)
                    )
                """)
            else:
                schema_editor.execute("""
                    CREATE TABLE `core_callerfavorite` (
                        `id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
                        `created_at` datetime(6) NOT NULL,
                        `agent_id` bigint NOT NULL,
                        `caller_id` bigint NOT NULL,
                        UNIQUE KEY `core_callerfavorite_caller_id_agent_id_uniq` (`caller_id`, `agent_id`),
                        KEY `core_callerfavorite_agent_id_idx` (`agent_id`),
                        KEY `core_callerfavorite_caller_id_idx` (`caller_id`),
                        CONSTRAINT `core_callerfavorite_agent_id_fk` FOREIGN KEY (`agent_id`) REFERENCES `core_user` (`id`),
                        CONSTRAINT `core_callerfavorite_caller_id_fk` FOREIGN KEY (`caller_id`) REFERENCES `core_user` (`id`)
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                """)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_callerprofile_privacy_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_favorite_table, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='CallerFavorite',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to=settings.AUTH_USER_MODEL)),
                        ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caller_favorites', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['-created_at'],
                        'unique_together': {('caller', 'agent')},
                    },
                ),
            ]
        ),
    ]
