# Generated by Django on 2026-09-08
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def sync_buddy_profiles_to_listeners(apps, schema_editor):
    """
    Data migration: copy any existing data from BuddyProfile into ListenerProfile
    so existing listeners/buddies keep their profession, bio, rating, etc.
    """
    try:
        BuddyProfile = apps.get_model('core', 'BuddyProfile')
        ListenerProfile = apps.get_model('core', 'ListenerProfile')
        AgentWallet = apps.get_model('core', 'AgentWallet')

        for bp in BuddyProfile.objects.select_related('user').all():
            if not bp.user:
                continue
            lp, _ = ListenerProfile.objects.get_or_create(
                user=bp.user,
                defaults={
                    'listener_id': bp.user.username,
                    'name': bp.user.first_name or bp.user.username,
                    'language': bp.languages or 'English',
                }
            )
            lp.profession = bp.profession
            lp.bio = bp.bio or ''
            lp.rating = bp.rating or 5.00
            lp.total_calls = bp.total_calls or 0
            lp.is_verified = bp.is_verified or False
            lp.is_busy = bp.is_busy or False
            lp.is_on_duty = bp.is_online or False
            # Convert rate_per_minute to rate_per_second
            if bp.rate_per_minute:
                sec_rate = max(1, round(bp.rate_per_minute / 60))
                lp.rate_per_second = sec_rate if sec_rate in (3, 5, 10) else 3
            lp.save()

            # Ensure AgentWallet exists
            AgentWallet.objects.get_or_create(agent=bp.user, defaults={'balance': 0})
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_callerfavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listenerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listenerprofile',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listenerprofile',
            name='is_on_duty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listenerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listenerprofile',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listeners', to='core.category'),
        ),
        migrations.AddField(
            model_name='listenerprofile',
            name='rate_per_second',
            field=models.PositiveIntegerField(choices=[(3, '3 Coins/sec'), (5, '5 Coins/sec'), (10, '10 Coins/sec')], default=3, help_text='Coins charged per second of call'),
        ),
        migrations.AddField(
            model_name='listenerprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='listenerprofile',
            name='total_calls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listenerprofile',
            name='total_earned_coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listenerprofile',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CALLER', 'Caller'), ('LISTENER', 'Listener'), ('AGENT', 'Agent'), ('ADMIN', 'Admin'), ('USER', 'Caller (Legacy)'), ('BUDDY', 'Listener (Legacy)')], db_index=True, default='CALLER', max_length=10),
        ),
        migrations.CreateModel(
            name='AgentWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, help_text='Current withdrawable coin balance')),
                ('total_earned', models.PositiveIntegerField(default=0, help_text='Lifetime earned coins')),
                ('total_paid_out', models.PositiveIntegerField(default=0, help_text='Lifetime paid out coins')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField(help_text='Coins to withdraw')),
                ('amount_inr', models.DecimalField(decimal_places=2, default=0.0, help_text='Equivalent amount in INR', max_digits=10)),
                ('payout_method', models.CharField(default='UPI', max_length=50)),
                ('payout_details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_type', models.CharField(choices=[('VOICE', 'Voice Call'), ('VIDEO', 'Video Call'), ('BONUS', 'Bonus'), ('ADJUSTMENT', 'Adjustment')], default='VOICE', max_length=20)),
                ('coins', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_earnings', to='core.call')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentDutySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.RunPython(sync_buddy_profiles_to_listeners, reverse_code=migrations.RunPython.noop),
    ]
