# Generated by Django 6.1 on 2026-09-11 09:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_agent_system_unification'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging device token', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agentearning',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agentearning',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
