"""
URL configuration for project project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/6.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

# pyrefly: ignore [missing-import]
from django.contrib import admin
# pyrefly: ignore [missing-import]
from django.urls import path, include
# pyrefly: ignore [missing-import]
from django.conf import settings
# pyrefly: ignore [missing-import]
from django.conf.urls.static import static

from core.views import (
    CallerLoginView,
    ListenerLoginView,
    CallerLogoutView,
    ListenerLogoutView,
    LogoutView,
    DeleteAccountView,
    AdminCreateListenerView,
    AdminListenerListView,
    AdminDeleteListenerView,
    CallerListCreateView,
    CallerDetailView,
    CallerUpdateView,
    CallerDeleteView,
    CallerDeleteDirectView,
    ListenerListCreateView,
    ListenerDetailView,
    ListenerDeleteView,
    ListenerDeleteDirectView,
    TermsAndConditionsView,
    CallerPrivacySettingsView,
    PrivacyPolicyView,
    HelplineView,
    ProfileView,
    CallerProfileView,
    WalletView,
    GetCoinsView,
    AddCoinsView,
    CallRequestView,
    IncomingCallsView,
    AcceptCallView,
    RejectCallView,
    StartCallView,
    EndCallView,
    CallHistoryView,
    CallDetailView,
    CallerAccountDeleteView,
)
from core.caller_views import app_home_view, admin_panel_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panel/', admin_panel_view, name='admin-panel'),
    path('admin-panel/', admin_panel_view, name='admin-panel-alias'),
    path('dashboard/', admin_panel_view, name='admin-dashboard'),
    path('', app_home_view, name='app-home'),
    path('app/', app_home_view, name='app-simulator'),
    path('simulator/', app_home_view, name='app-simulator-alias'),

    # ==========================================
    # CALLER CRUD ENDPOINTS
    # ==========================================
    path('api/callers/', CallerListCreateView.as_view(), name='api-direct-callers'),
    path('api/callers', CallerListCreateView.as_view()),
    path('callers/', CallerListCreateView.as_view()),
    path('callers', CallerListCreateView.as_view()),
    path('api/callers/<int:user_id>/delete/', CallerDeleteView.as_view(), name='api-caller-delete'),
    path('api/callers/<int:user_id>/delete', CallerDeleteView.as_view()),
    path('callers/<int:user_id>/delete/', CallerDeleteView.as_view()),
    path('callers/<int:user_id>/delete', CallerDeleteView.as_view()),
    path('api/callers/<str:identifier>/', CallerDetailView.as_view()),
    path('api/callers/<str:identifier>', CallerDetailView.as_view()),
    path('callers/<str:identifier>/', CallerDetailView.as_view()),
    path('callers/<str:identifier>', CallerDetailView.as_view()),
    path('api/callers/<str:identifier>/delete/', CallerDeleteDirectView.as_view()),
    path('api/callers/<str:identifier>/delete', CallerDeleteDirectView.as_view()),
    path('callers/<str:identifier>/delete/', CallerDeleteDirectView.as_view()),
    path('callers/<str:identifier>/delete', CallerDeleteDirectView.as_view()),

    # Dedicated Caller Update routes (direct top-level & /api/)
    path('api/callerupdate/', CallerUpdateView.as_view(), name='api-caller-update'),
    path('api/callerupdate', CallerUpdateView.as_view()),
    path('api/callerupdate/<str:identifier>/', CallerUpdateView.as_view()),
    path('api/callerupdate/<str:identifier>', CallerUpdateView.as_view()),
    path('callerupdate/', CallerUpdateView.as_view()),
    path('callerupdate', CallerUpdateView.as_view()),
    path('callerupdate/<str:identifier>/', CallerUpdateView.as_view()),
    path('callerupdate/<str:identifier>', CallerUpdateView.as_view()),
    path('api/caller-update/', CallerUpdateView.as_view()),
    path('api/caller-update', CallerUpdateView.as_view()),
    path('caller-update/', CallerUpdateView.as_view()),
    path('caller-update', CallerUpdateView.as_view()),
    path('api/caller/update/', CallerUpdateView.as_view()),
    path('api/caller/update', CallerUpdateView.as_view()),
    path('caller/update/', CallerUpdateView.as_view()),
    path('caller/update', CallerUpdateView.as_view()),
    path('api/api/callerupdate/', CallerUpdateView.as_view()),
    path('api/api/callerupdate', CallerUpdateView.as_view()),

    # Dedicated Caller Delete routes (direct top-level & /api/)
    path('api/callerdelete/', CallerDeleteView.as_view(), name='api-caller-delete-direct'),
    path('api/callerdelete', CallerDeleteView.as_view()),
    path('api/callerdelete/<str:identifier>/', CallerDeleteView.as_view()),
    path('api/callerdelete/<str:identifier>', CallerDeleteView.as_view()),
    path('callerdelete/', CallerDeleteView.as_view()),
    path('callerdelete', CallerDeleteView.as_view()),
    path('callerdelete/<str:identifier>/', CallerDeleteView.as_view()),
    path('callerdelete/<str:identifier>', CallerDeleteView.as_view()),
    path('api/caller-delete/', CallerDeleteView.as_view()),
    path('api/caller-delete', CallerDeleteView.as_view()),
    path('caller-delete/', CallerDeleteView.as_view()),
    path('caller-delete', CallerDeleteView.as_view()),
    path('api/caller/delete/', CallerDeleteView.as_view()),
    path('api/caller/delete', CallerDeleteView.as_view()),
    path('caller/delete/', CallerDeleteView.as_view()),
    path('caller/delete', CallerDeleteView.as_view()),
    path('api/api/callerdelete/', CallerDeleteView.as_view()),
    path('api/api/callerdelete', CallerDeleteView.as_view()),

    # ==========================================
    # LISTENER CRUD ENDPOINTS (ALL VARIATIONS)
    # ==========================================
    path('api/listeners/', ListenerListCreateView.as_view(), name='api-direct-listeners'),
    path('api/listeners', ListenerListCreateView.as_view()),
    path('listeners/', ListenerListCreateView.as_view()),
    path('listeners', ListenerListCreateView.as_view()),
    path('api/listeners/<int:user_id>/delete/', ListenerDeleteView.as_view(), name='api-listener-delete'),
    path('api/listeners/<int:user_id>/delete', ListenerDeleteView.as_view()),
    path('listeners/<int:user_id>/delete/', ListenerDeleteView.as_view()),
    path('listeners/<int:user_id>/delete', ListenerDeleteView.as_view()),
    path('api/listeners/<str:identifier>/', ListenerDetailView.as_view()),
    path('api/listeners/<str:identifier>', ListenerDetailView.as_view()),
    path('listeners/<str:identifier>/', ListenerDetailView.as_view()),
    path('listeners/<str:identifier>', ListenerDetailView.as_view()),
    path('api/listeners/<str:identifier>/delete/', ListenerDeleteDirectView.as_view()),
    path('api/listeners/<str:identifier>/delete', ListenerDeleteDirectView.as_view()),
    path('listeners/<str:identifier>/delete/', ListenerDeleteDirectView.as_view()),
    path('listeners/<str:identifier>/delete', ListenerDeleteDirectView.as_view()),
    path('api/listeners/create/', AdminCreateListenerView.as_view()),
    path('api/listeners/create', AdminCreateListenerView.as_view()),
    path('listeners/create/', AdminCreateListenerView.as_view()),
    path('listeners/create', AdminCreateListenerView.as_view()),
    path('api/listeners/delete/', AdminDeleteListenerView.as_view()),
    path('api/listeners/delete', AdminDeleteListenerView.as_view()),
    path('listeners/delete/', AdminDeleteListenerView.as_view()),
    path('listeners/delete', AdminDeleteListenerView.as_view()),
    path('api/listeners/delete/<str:identifier>/', AdminDeleteListenerView.as_view()),
    path('api/listeners/delete/<str:identifier>', AdminDeleteListenerView.as_view()),
    path('listeners/delete/<str:identifier>/', AdminDeleteListenerView.as_view()),
    path('listeners/delete/<str:identifier>', AdminDeleteListenerView.as_view()),

    # Admin aliases
    path('api/admin/listeners/', AdminListenerListView.as_view()),
    path('api/admin/listeners', AdminListenerListView.as_view()),
    path('admin/listeners/', AdminListenerListView.as_view()),
    path('admin/listeners', AdminListenerListView.as_view()),
    path('api/admin/listeners/create/', AdminCreateListenerView.as_view()),
    path('api/admin/listeners/create', AdminCreateListenerView.as_view()),
    path('admin/listeners/create/', AdminCreateListenerView.as_view()),
    path('admin/listeners/create', AdminCreateListenerView.as_view()),
    path('api/admin/listeners/delete/', AdminDeleteListenerView.as_view()),
    path('api/admin/listeners/delete', AdminDeleteListenerView.as_view()),
    path('admin/listeners/delete/', AdminDeleteListenerView.as_view()),
    path('admin/listeners/delete', AdminDeleteListenerView.as_view()),
    path('api/admin/listeners/delete/<str:identifier>/', AdminDeleteListenerView.as_view()),
    path('api/admin/listeners/delete/<str:identifier>', AdminDeleteListenerView.as_view()),
    path('admin/listeners/delete/<str:identifier>/', AdminDeleteListenerView.as_view()),
    path('admin/listeners/delete/<str:identifier>', AdminDeleteListenerView.as_view()),
    path('api/admin/listeners/<str:identifier>/', ListenerDetailView.as_view()),
    path('api/admin/listeners/<str:identifier>', ListenerDetailView.as_view()),
    path('admin/listeners/<str:identifier>/', ListenerDetailView.as_view()),
    path('admin/listeners/<str:identifier>', ListenerDetailView.as_view()),


    # Direct Caller Login endpoints (handles all URL variations)
    path('api/auth/caller/login/', CallerLoginView.as_view(), name='api-auth-caller-login'),
    path('api/auth/caller/login', CallerLoginView.as_view()),
    path('auth/caller/login/', CallerLoginView.as_view()),
    path('auth/caller/login', CallerLoginView.as_view()),
    path('api/caller/login/', CallerLoginView.as_view()),
    path('api/caller/login', CallerLoginView.as_view()),
    path('caller/login/', CallerLoginView.as_view()),
    path('caller/login', CallerLoginView.as_view()),
    path('api/api/auth/caller/login/', CallerLoginView.as_view()),
    path('api/api/auth/caller/login', CallerLoginView.as_view()),
    path('api/api/caller/login/', CallerLoginView.as_view()),
    path('api/api/caller/login', CallerLoginView.as_view()),

    # Direct Listener & General Login endpoints (handles all URL variations)
    path('api/auth/listener/login/', ListenerLoginView.as_view(), name='api-auth-listener-login'),
    path('api/auth/listener/login', ListenerLoginView.as_view()),
    path('auth/listener/login/', ListenerLoginView.as_view()),
    path('auth/listener/login', ListenerLoginView.as_view()),
    path('api/listener/login/', ListenerLoginView.as_view()),
    path('api/listener/login', ListenerLoginView.as_view()),
    path('listener/login/', ListenerLoginView.as_view()),
    path('listener/login', ListenerLoginView.as_view()),

    # General login aliases
    path('api/auth/login/', ListenerLoginView.as_view()),
    path('api/auth/login', ListenerLoginView.as_view()),
    path('auth/login/', ListenerLoginView.as_view()),
    path('auth/login', ListenerLoginView.as_view()),
    path('api/login/', ListenerLoginView.as_view()),
    path('api/login', ListenerLoginView.as_view()),
    path('login/', ListenerLoginView.as_view()),
    path('login', ListenerLoginView.as_view()),

    # Caller logout aliases
    path('api/auth/caller/logout/', CallerLogoutView.as_view(), name='api-auth-caller-logout'),
    path('api/auth/caller/logout', CallerLogoutView.as_view()),
    path('auth/caller/logout/', CallerLogoutView.as_view()),
    path('auth/caller/logout', CallerLogoutView.as_view()),
    path('api/caller/logout/', CallerLogoutView.as_view()),
    path('api/caller/logout', CallerLogoutView.as_view()),
    path('caller/logout/', CallerLogoutView.as_view()),
    path('caller/logout', CallerLogoutView.as_view()),

    # Listener logout aliases
    path('api/auth/listener/logout/', ListenerLogoutView.as_view(), name='api-auth-listener-logout'),
    path('api/auth/listener/logout', ListenerLogoutView.as_view()),
    path('auth/listener/logout/', ListenerLogoutView.as_view()),
    path('auth/listener/logout', ListenerLogoutView.as_view()),
    path('api/listener/logout/', ListenerLogoutView.as_view()),
    path('api/listener/logout', ListenerLogoutView.as_view()),
    path('listener/logout/', ListenerLogoutView.as_view()),
    path('listener/logout', ListenerLogoutView.as_view()),
    path('api/listenerlogout/', ListenerLogoutView.as_view(), name='api-listenerlogout'),
    path('api/listenerlogout', ListenerLogoutView.as_view()),
    path('listenerlogout/', ListenerLogoutView.as_view()),
    path('listenerlogout', ListenerLogoutView.as_view()),
    path('api/listener-logout/', ListenerLogoutView.as_view()),
    path('api/listener-logout', ListenerLogoutView.as_view()),
    path('listener-logout/', ListenerLogoutView.as_view()),
    path('listener-logout', ListenerLogoutView.as_view()),
    path('api/api/listener/logout/', ListenerLogoutView.as_view()),
    path('api/api/listener/logout', ListenerLogoutView.as_view()),
    path('api/api/listenerlogout/', ListenerLogoutView.as_view()),
    path('api/api/listenerlogout', ListenerLogoutView.as_view()),

    # General logout aliases
    path('api/auth/logout/', LogoutView.as_view(), name='api-auth-logout'),
    path('api/auth/logout', LogoutView.as_view()),
    path('auth/logout/', LogoutView.as_view()),
    path('auth/logout', LogoutView.as_view()),
    path('api/logout/', LogoutView.as_view()),
    path('api/logout', LogoutView.as_view()),
    path('logout/', LogoutView.as_view()),
    path('logout', LogoutView.as_view()),

    # General delete account aliases
    path('api/auth/delete-account/', DeleteAccountView.as_view(), name='api-auth-delete-account'),
    path('api/auth/delete-account', DeleteAccountView.as_view()),
    path('auth/delete-account/', DeleteAccountView.as_view()),
    path('auth/delete-account', DeleteAccountView.as_view()),
    path('api/delete-account/', DeleteAccountView.as_view()),
    path('api/delete-account', DeleteAccountView.as_view()),
    path('delete-account/', DeleteAccountView.as_view()),
    path('delete-account', DeleteAccountView.as_view()),
    path('api/profile/delete/', DeleteAccountView.as_view()),
    path('api/profile/delete', DeleteAccountView.as_view()),
    path('profile/delete/', DeleteAccountView.as_view()),
    path('profile/delete', DeleteAccountView.as_view()),

    # ==========================================
    # LEGAL & HELPLINE ROUTES
    # ==========================================
    path('api/helpline/', HelplineView.as_view(), name='api-helpline'),
    path('api/helpline', HelplineView.as_view()),
    path('api/api/helpline/', HelplineView.as_view()),
    path('api/api/helpline', HelplineView.as_view()),
    path('helpline/', HelplineView.as_view()),
    path('helpline', HelplineView.as_view()),
    path('api/support/', HelplineView.as_view()),
    path('api/support', HelplineView.as_view()),
    path('support/', HelplineView.as_view()),
    path('support', HelplineView.as_view()),

    path('api/terms-and-conditions/', TermsAndConditionsView.as_view(), name='api-terms-and-conditions'),
    path('api/terms-and-conditions', TermsAndConditionsView.as_view()),
    path('api/api/terms-and-conditions/', TermsAndConditionsView.as_view()),
    path('api/api/terms-and-conditions', TermsAndConditionsView.as_view()),
    path('terms-and-conditions/', TermsAndConditionsView.as_view()),
    path('terms-and-conditions', TermsAndConditionsView.as_view()),
    path('api/terms/', TermsAndConditionsView.as_view()),
    path('api/terms', TermsAndConditionsView.as_view()),
    path('terms/', TermsAndConditionsView.as_view()),
    path('terms', TermsAndConditionsView.as_view()),

    path('api/privacy/', CallerPrivacySettingsView.as_view(), name='api-privacy'),
    path('api/privacy', CallerPrivacySettingsView.as_view()),
    path('privacy/', CallerPrivacySettingsView.as_view()),
    path('privacy', CallerPrivacySettingsView.as_view()),
    path('api/api/privacy/', CallerPrivacySettingsView.as_view()),
    path('api/api/privacy', CallerPrivacySettingsView.as_view()),
    path('api/privacy-policy/', CallerPrivacySettingsView.as_view(), name='api-privacy-policy'),
    path('api/privacy-policy', CallerPrivacySettingsView.as_view()),
    path('api/api/privacy-policy/', CallerPrivacySettingsView.as_view()),
    path('api/api/privacy-policy', CallerPrivacySettingsView.as_view()),
    path('privacy-policy/', CallerPrivacySettingsView.as_view()),
    path('privacy-policy', CallerPrivacySettingsView.as_view()),

    # ==========================================
    # CALLER PROFILE ROUTES (ALL VARIATIONS)
    # ==========================================
    path('api/profile/', ProfileView.as_view(), name='api-profile'),
    path('api/profile', ProfileView.as_view()),
    path('api/profile/<str:identifier>/', ProfileView.as_view()),
    path('api/profile/<str:identifier>', ProfileView.as_view()),
    path('profile/', ProfileView.as_view()),
    path('profile', ProfileView.as_view()),
    path('profile/<str:identifier>/', ProfileView.as_view()),
    path('profile/<str:identifier>', ProfileView.as_view()),

    path('api/caller/profile/', CallerProfileView.as_view(), name='api-caller-profile'),
    path('api/caller/profile', CallerProfileView.as_view()),
    path('api/caller/profile/<str:identifier>/', ProfileView.as_view()),
    path('api/caller/profile/<str:identifier>', ProfileView.as_view()),
    path('caller/profile/', CallerProfileView.as_view()),
    path('caller/profile', CallerProfileView.as_view()),
    path('caller/profile/<str:identifier>/', ProfileView.as_view()),
    path('caller/profile/<str:identifier>', ProfileView.as_view()),

    # My Account: Wallet & Coins endpoints
    path('api/wallet/', WalletView.as_view(), name='api-wallet'),
    path('api/wallet', WalletView.as_view()),
    path('wallet/', WalletView.as_view()),
    path('wallet', WalletView.as_view()),
    path('api/wallet/coins/', GetCoinsView.as_view()),
    path('api/wallet/coins', GetCoinsView.as_view()),
    path('wallet/coins/', GetCoinsView.as_view()),
    path('wallet/coins', GetCoinsView.as_view()),

    # Get Coins endpoints
    path('api/coins/', GetCoinsView.as_view(), name='api-coins'),
    path('api/coins', GetCoinsView.as_view()),
    path('coins/', GetCoinsView.as_view()),
    path('coins', GetCoinsView.as_view()),
    path('api/get-coins/', GetCoinsView.as_view()),
    path('api/get-coins', GetCoinsView.as_view()),
    path('get-coins/', GetCoinsView.as_view()),
    path('get-coins', GetCoinsView.as_view()),
    path('api/getcoins/', GetCoinsView.as_view()),
    path('api/getcoins', GetCoinsView.as_view()),
    path('getcoins/', GetCoinsView.as_view()),
    path('getcoins', GetCoinsView.as_view()),

    # Add Coins endpoints
    path('api/coins/add/', AddCoinsView.as_view(), name='api-coins-add'),
    path('api/coins/add', AddCoinsView.as_view()),
    path('coins/add/', AddCoinsView.as_view()),
    path('coins/add', AddCoinsView.as_view()),
    path('api/add-coins/', AddCoinsView.as_view()),
    path('api/add-coins', AddCoinsView.as_view()),
    path('add-coins/', AddCoinsView.as_view()),
    path('add-coins', AddCoinsView.as_view()),
    path('api/addcoins/', AddCoinsView.as_view()),
    path('api/addcoins', AddCoinsView.as_view()),
    path('addcoins/', AddCoinsView.as_view()),
    path('addcoins', AddCoinsView.as_view()),

    # Double-prefix safety for coins
    path('api/api/coins/', GetCoinsView.as_view()),
    path('api/api/coins', GetCoinsView.as_view()),
    path('api/api/coins/add/', AddCoinsView.as_view()),
    path('api/api/coins/add', AddCoinsView.as_view()),
    path('api/api/add-coins/', AddCoinsView.as_view()),
    path('api/api/add-coins', AddCoinsView.as_view()),
    path('api/api/addcoins/', AddCoinsView.as_view()),
    path('api/api/addcoins', AddCoinsView.as_view()),
    path('api/api/get-coins/', GetCoinsView.as_view()),
    path('api/api/get-coins', GetCoinsView.as_view()),
    path('api/api/getcoins/', GetCoinsView.as_view()),
    path('api/api/getcoins', GetCoinsView.as_view()),

    # Call Workflow endpoints (Plural & Singular)
    path('api/calls/request/', CallRequestView.as_view(), name='api-call-request'),
    path('api/calls/request', CallRequestView.as_view()),
    path('calls/request/', CallRequestView.as_view()),
    path('calls/request', CallRequestView.as_view()),
    path('api/call/request/', CallRequestView.as_view()),
    path('api/call/request', CallRequestView.as_view()),
    path('call/request/', CallRequestView.as_view()),
    path('call/request', CallRequestView.as_view()),
    path('api/callrequest/', CallRequestView.as_view()),
    path('api/callrequest', CallRequestView.as_view()),
    path('api/call-request/', CallRequestView.as_view()),
    path('api/call-request', CallRequestView.as_view()),

    path('api/calls/incoming/', IncomingCallsView.as_view(), name='api-calls-incoming'),
    path('api/calls/incoming', IncomingCallsView.as_view()),
    path('calls/incoming/', IncomingCallsView.as_view()),
    path('calls/incoming', IncomingCallsView.as_view()),
    path('api/call/incoming/', IncomingCallsView.as_view()),
    path('api/call/incoming', IncomingCallsView.as_view()),
    path('call/incoming/', IncomingCallsView.as_view()),
    path('call/incoming', IncomingCallsView.as_view()),

    path('api/calls/<int:call_id>/accept/', AcceptCallView.as_view(), name='api-call-accept'),
    path('api/calls/<int:call_id>/accept', AcceptCallView.as_view()),
    path('calls/<int:call_id>/accept/', AcceptCallView.as_view()),
    path('calls/<int:call_id>/accept', AcceptCallView.as_view()),
    path('api/call/<int:call_id>/accept/', AcceptCallView.as_view()),
    path('api/call/<int:call_id>/accept', AcceptCallView.as_view()),
    path('call/<int:call_id>/accept/', AcceptCallView.as_view()),
    path('call/<int:call_id>/accept', AcceptCallView.as_view()),

    path('api/calls/<int:call_id>/reject/', RejectCallView.as_view(), name='api-call-reject'),
    path('api/calls/<int:call_id>/reject', RejectCallView.as_view()),
    path('calls/<int:call_id>/reject/', RejectCallView.as_view()),
    path('calls/<int:call_id>/reject', RejectCallView.as_view()),
    path('api/call/<int:call_id>/reject/', RejectCallView.as_view()),
    path('api/call/<int:call_id>/reject', RejectCallView.as_view()),
    path('call/<int:call_id>/reject/', RejectCallView.as_view()),
    path('call/<int:call_id>/reject', RejectCallView.as_view()),

    path('api/calls/<int:call_id>/start/', StartCallView.as_view(), name='api-call-start'),
    path('api/calls/<int:call_id>/start', StartCallView.as_view()),
    path('calls/<int:call_id>/start/', StartCallView.as_view()),
    path('calls/<int:call_id>/start', StartCallView.as_view()),
    path('api/call/<int:call_id>/start/', StartCallView.as_view()),
    path('api/call/<int:call_id>/start', StartCallView.as_view()),
    path('call/<int:call_id>/start/', StartCallView.as_view()),
    path('call/<int:call_id>/start', StartCallView.as_view()),

    path('api/calls/<int:call_id>/end/', EndCallView.as_view(), name='api-call-end'),
    path('api/calls/<int:call_id>/end', EndCallView.as_view()),
    path('calls/<int:call_id>/end/', EndCallView.as_view()),
    path('calls/<int:call_id>/end', EndCallView.as_view()),
    path('api/call/<int:call_id>/end/', EndCallView.as_view()),
    path('api/call/<int:call_id>/end', EndCallView.as_view()),
    path('call/<int:call_id>/end/', EndCallView.as_view()),
    path('call/<int:call_id>/end', EndCallView.as_view()),

    # Double-prefix safety for call workflow
    path('api/api/calls/request/', CallRequestView.as_view()),
    path('api/api/calls/request', CallRequestView.as_view()),
    path('api/api/call/request/', CallRequestView.as_view()),
    path('api/api/call/request', CallRequestView.as_view()),
    path('api/api/calls/incoming/', IncomingCallsView.as_view()),
    path('api/api/calls/incoming', IncomingCallsView.as_view()),
    path('api/api/call/incoming/', IncomingCallsView.as_view()),
    path('api/api/call/incoming', IncomingCallsView.as_view()),
    path('api/api/calls/<int:call_id>/accept/', AcceptCallView.as_view()),
    path('api/api/calls/<int:call_id>/accept', AcceptCallView.as_view()),
    path('api/api/call/<int:call_id>/accept/', AcceptCallView.as_view()),
    path('api/api/call/<int:call_id>/accept', AcceptCallView.as_view()),
    path('api/api/calls/<int:call_id>/reject/', RejectCallView.as_view()),
    path('api/api/calls/<int:call_id>/reject', RejectCallView.as_view()),
    path('api/api/call/<int:call_id>/reject/', RejectCallView.as_view()),
    path('api/api/call/<int:call_id>/reject', RejectCallView.as_view()),
    path('api/api/calls/<int:call_id>/start/', StartCallView.as_view()),
    path('api/api/calls/<int:call_id>/start', StartCallView.as_view()),
    path('api/api/call/<int:call_id>/start/', StartCallView.as_view()),
    path('api/api/call/<int:call_id>/start', StartCallView.as_view()),
    path('api/api/calls/<int:call_id>/end/', EndCallView.as_view()),
    path('api/api/calls/<int:call_id>/end', EndCallView.as_view()),
    path('api/api/call/<int:call_id>/end/', EndCallView.as_view()),
    path('api/api/call/<int:call_id>/end', EndCallView.as_view()),

    # Call History endpoints
    path('api/calls/history/', CallHistoryView.as_view(), name='api-calls-history'),
    path('api/calls/history', CallHistoryView.as_view()),
    path('calls/history/', CallHistoryView.as_view()),
    path('calls/history', CallHistoryView.as_view()),
    path('api/callhistory/', CallHistoryView.as_view(), name='api-call-history'),
    path('api/callhistory', CallHistoryView.as_view()),
    path('callhistory/', CallHistoryView.as_view()),
    path('callhistory', CallHistoryView.as_view()),
    path('api/call-history/', CallHistoryView.as_view()),
    path('api/call-history', CallHistoryView.as_view()),
    path('call-history/', CallHistoryView.as_view()),
    path('call-history', CallHistoryView.as_view()),
    path('api/calls/', CallHistoryView.as_view()),
    path('api/calls', CallHistoryView.as_view()),
    path('calls/', CallHistoryView.as_view()),
    path('calls', CallHistoryView.as_view()),
    path('api/callhistory/<int:call_id>/', CallDetailView.as_view()),
    path('api/callhistory/<int:call_id>', CallDetailView.as_view()),
    path('callhistory/<int:call_id>/', CallDetailView.as_view()),
    path('callhistory/<int:call_id>', CallDetailView.as_view()),
    path('api/call-history/<int:call_id>/', CallDetailView.as_view()),
    path('api/call-history/<int:call_id>', CallDetailView.as_view()),
    path('call-history/<int:call_id>/', CallDetailView.as_view()),
    path('call-history/<int:call_id>', CallDetailView.as_view()),

    # Double-prefix safety for call history
    path('api/api/calls/history/', CallHistoryView.as_view()),
    path('api/api/calls/history', CallHistoryView.as_view()),
    path('api/api/callhistory/', CallHistoryView.as_view()),
    path('api/api/callhistory', CallHistoryView.as_view()),
    path('api/api/call-history/', CallHistoryView.as_view()),
    path('api/api/call-history', CallHistoryView.as_view()),

    path('api/caller/account/', CallerAccountDeleteView.as_view(), name='api-caller-account-delete'),
    path('api/caller/account', CallerAccountDeleteView.as_view()),
    path('caller/account/', CallerAccountDeleteView.as_view()),
    path('caller/account', CallerAccountDeleteView.as_view()),

    path('api/callerprofileview/', CallerProfileView.as_view(), name='api-callerprofileview'),
    path('api/callerprofileview', CallerProfileView.as_view()),
    path('api/callerprofileview/<str:identifier>/', CallerProfileView.as_view()),
    path('api/callerprofileview/<str:identifier>', CallerProfileView.as_view()),
    path('callerprofileview/', CallerProfileView.as_view()),
    path('callerprofileview', CallerProfileView.as_view()),
    path('callerprofileview/<str:identifier>/', CallerProfileView.as_view()),
    path('callerprofileview/<str:identifier>', CallerProfileView.as_view()),

    path('api/callerprofile/', CallerProfileView.as_view(), name='api-callerprofile'),
    path('api/callerprofile', CallerProfileView.as_view()),
    path('api/callerprofile/<str:identifier>/', CallerProfileView.as_view()),
    path('api/callerprofile/<str:identifier>', CallerProfileView.as_view()),
    path('callerprofile/', CallerProfileView.as_view()),
    path('callerprofile', CallerProfileView.as_view()),
    path('callerprofile/<str:identifier>/', CallerProfileView.as_view()),
    path('callerprofile/<str:identifier>', CallerProfileView.as_view()),

    path('api/caller-profile/', CallerProfileView.as_view()),
    path('api/caller-profile', CallerProfileView.as_view()),
    path('caller-profile/', CallerProfileView.as_view()),
    path('caller-profile', CallerProfileView.as_view()),

    # Double-prefix safety (for Postman environment baseUrl with /api)
    path('api/api/profile/', ProfileView.as_view()),
    path('api/api/profile', ProfileView.as_view()),
    path('api/api/caller/profile/', CallerProfileView.as_view()),
    path('api/api/caller/profile', CallerProfileView.as_view()),
    path('api/api/wallet/', WalletView.as_view()),
    path('api/api/wallet', WalletView.as_view()),
    path('api/api/caller/account/', CallerAccountDeleteView.as_view()),
    path('api/api/caller/account', CallerAccountDeleteView.as_view()),
    path('api/api/callerprofileview/', CallerProfileView.as_view()),
    path('api/api/callerprofileview', CallerProfileView.as_view()),

    # Standard App routing
    path('api/', include('core.urls')),
    path('', include('core.urls')),
]


# Serve user-uploaded media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

