"""
URL configuration for project project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/6.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

# pyrefly: ignore [missing-import]
from django.contrib import admin
# pyrefly: ignore [missing-import]
from django.urls import path, include
# pyrefly: ignore [missing-import]
from django.conf import settings
# pyrefly: ignore [missing-import]
from django.conf.urls.static import static

from core.views import (
    CallerLoginView,
    ListenerLoginView,
    CallerLogoutView,
    ListenerLogoutView,
    LogoutView,
    DeleteAccountView,
    AdminCreateListenerView,
    AdminListenerListView,
    AdminDeleteListenerView,
    CallerListCreateView,
    CallerDetailView,
    CallerUpdateView,
    CallerDeleteView,
    CallerDeleteDirectView,
    ListenerListCreateView,
    ListenerDetailView,
    ListenerDeleteView,
    ListenerDeleteDirectView,
    TermsAndConditionsView,
    CallerPrivacySettingsView,
    PrivacyPolicyView,
    HelplineView,
    ProfileView,
    CallerProfileView,
    WalletView,
    GetCoinsView,
    AddCoinsView,
    CoinPurchaseHistoryView,
    CoinTransactionHistoryView,
    CallRequestView,
    IncomingCallsView,
    AcceptCallView,
    RejectCallView,
    StartCallView,
    EndCallView,
    AgoraCallTokenView,
    CallHistoryView,
    CallDetailView,
    CallerAccountDeleteView,
    CallerFavoritesView,
    CallerFavoriteDetailView,
    AgentLoginView,
    AgentLogoutView,
    AgentForgotPasswordView,
    AgentResetPasswordView,
    AgentProfileView,
    AgentProfessionsView,
    AgentRateView,
    AgentDutyView,
    AgentDutyOnView,
    AgentDutyOffView,
    AgentDashboardView,
    AgentEarningsTodayView,
    AgentEarningsHistoryView,
    AgentWalletView,
    AgentPayoutView,
    AgentRatingView,
    AgentRecentSessionsView,
)
from core.caller_views import app_home_view, admin_panel_view, admin_live_data_api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panel/', admin_panel_view, name='admin-panel'),
    path('admin-panel/', admin_panel_view, name='admin-panel-alias'),
    path('dashboard/', admin_panel_view, name='admin-dashboard'),
    path('api/admin/live-data/', admin_live_data_api, name='admin-live-data'),
    path('api/admin/live-data', admin_live_data_api),
    path('admin/live-data/', admin_live_data_api),
    path('admin/live-data', admin_live_data_api),
    path('', app_home_view, name='app-home'),
    path('app/', app_home_view, name='app-simulator'),
    path('simulator/', app_home_view, name='app-simulator-alias'),

    # ==========================================
    # CALLER CRUD ENDPOINTS
    # ==========================================
    path('api/callers/', CallerListCreateView.as_view(), name='api-direct-callers'),
    path('api/callers', CallerListCreateView.as_view()),
    path('callers/', CallerListCreateView.as_view()),
    path('callers', CallerListCreateView.as_view()),
    path('api/callers/<int:user_id>/delete/', CallerDeleteView.as_view(), name='api-caller-delete'),
    path('api/callers/<int:user_id>/delete', CallerDeleteView.as_view()),
    path('callers/<int:user_id>/delete/', CallerDeleteView.as_view()),
    path('callers/<int:user_id>/delete', CallerDeleteView.as_view()),
    path('api/callers/<str:identifier>/', CallerDetailView.as_view()),
    path('api/callers/<str:identifier>', CallerDetailView.as_view()),
    path('callers/<str:identifier>/', CallerDetailView.as_view()),
    path('callers/<str:identifier>', CallerDetailView.as_view()),
    path('api/callers/<str:identifier>/delete/', CallerDeleteDirectView.as_view()),
    path('api/callers/<str:identifier>/delete', CallerDeleteDirectView.as_view()),
    path('callers/<str:identifier>/delete/', CallerDeleteDirectView.as_view()),
    path('callers/<str:identifier>/delete', CallerDeleteDirectView.as_view()),

    # Dedicated Caller Update routes (direct top-level & /api/)
    path('api/callerupdate/', CallerUpdateView.as_view(), name='api-caller-update'),
    path('api/callerupdate', CallerUpdateView.as_view()),
    path('api/callerupdate/<str:identifier>/', CallerUpdateView.as_view()),
    path('api/callerupdate/<str:identifier>', CallerUpdateView.as_view()),
    path('callerupdate/', CallerUpdateView.as_view()),
    path('callerupdate', CallerUpdateView.as_view()),
    path('callerupdate/<str:identifier>/', CallerUpdateView.as_view()),
    path('callerupdate/<str:identifier>', CallerUpdateView.as_view()),
    path('api/caller-update/', CallerUpdateView.as_view()),
    path('api/caller-update', CallerUpdateView.as_view()),
    path('caller-update/', CallerUpdateView.as_view()),
    path('caller-update', CallerUpdateView.as_view()),
    path('api/caller/update/', CallerUpdateView.as_view()),
    path('api/caller/update', CallerUpdateView.as_view()),
    path('caller/update/', CallerUpdateView.as_view()),
    path('caller/update', CallerUpdateView.as_view()),
    path('api/api/callerupdate/', CallerUpdateView.as_view()),
    path('api/api/callerupdate', CallerUpdateView.as_view()),

    # Dedicated Caller Delete routes (direct top-level & /api/)
    path('api/callerdelete/', CallerDeleteView.as_view(), name='api-caller-delete-direct'),
    path('api/callerdelete', CallerDeleteView.as_view()),
    path('api/callerdelete/<str:identifier>/', CallerDeleteView.as_view()),
    path('api/callerdelete/<str:identifier>', CallerDeleteView.as_view()),
    path('callerdelete/', CallerDeleteView.as_view()),
    path('callerdelete', CallerDeleteView.as_view()),
    path('callerdelete/<str:identifier>/', CallerDeleteView.as_view()),
    path('callerdelete/<str:identifier>', CallerDeleteView.as_view()),
    path('api/caller-delete/', CallerDeleteView.as_view()),
    path('api/caller-delete', CallerDeleteView.as_view()),
    path('caller-delete/', CallerDeleteView.as_view()),
    path('caller-delete', CallerDeleteView.as_view()),
    path('api/caller/delete/', CallerDeleteView.as_view()),
    path('api/caller/delete', CallerDeleteView.as_view()),
    path('caller/delete/', CallerDeleteView.as_view()),
    path('caller/delete', CallerDeleteView.as_view()),
    path('api/api/callerdelete/', CallerDeleteView.as_view()),
    path('api/api/callerdelete', CallerDeleteView.as_view()),

    # ==========================================
    # LISTENER CRUD ENDPOINTS (ALL VARIATIONS)
    # ==========================================
    path('api/listeners/', ListenerListCreateView.as_view(), name='api-direct-listeners'),
    path('api/listeners', ListenerListCreateView.as_view()),
    path('listeners/', ListenerListCreateView.as_view()),
    path('listeners', ListenerListCreateView.as_view()),
    path('api/listeners/<int:user_id>/delete/', ListenerDeleteView.as_view(), name='api-listener-delete'),
    path('api/listeners/<int:user_id>/delete', ListenerDeleteView.as_view()),
    path('listeners/<int:user_id>/delete/', ListenerDeleteView.as_view()),
    path('listeners/<int:user_id>/delete', ListenerDeleteView.as_view()),
    path('api/listeners/<str:identifier>/', ListenerDetailView.as_view()),
    path('api/listeners/<str:identifier>', ListenerDetailView.as_view()),
    path('listeners/<str:identifier>/', ListenerDetailView.as_view()),
    path('listeners/<str:identifier>', ListenerDetailView.as_view()),
    path('api/listeners/<str:identifier>/delete/', ListenerDeleteDirectView.as_view()),
    path('api/listeners/<str:identifier>/delete', ListenerDeleteDirectView.as_view()),
    path('listeners/<str:identifier>/delete/', ListenerDeleteDirectView.as_view()),
    path('listeners/<str:identifier>/delete', ListenerDeleteDirectView.as_view()),
    path('api/listeners/create/', AdminCreateListenerView.as_view()),
    path('api/listeners/create', AdminCreateListenerView.as_view()),
    path('listeners/create/', AdminCreateListenerView.as_view()),
    path('listeners/create', AdminCreateListenerView.as_view()),
    path('api/listeners/delete/', AdminDeleteListenerView.as_view()),
    path('api/listeners/delete', AdminDeleteListenerView.as_view()),
    path('listeners/delete/', AdminDeleteListenerView.as_view()),
    path('listeners/delete', AdminDeleteListenerView.as_view()),
    path('api/listeners/delete/<str:identifier>/', AdminDeleteListenerView.as_view()),
    path('api/listeners/delete/<str:identifier>', AdminDeleteListenerView.as_view()),
    path('listeners/delete/<str:identifier>/', AdminDeleteListenerView.as_view()),
    path('listeners/delete/<str:identifier>', AdminDeleteListenerView.as_view()),

    # Admin aliases
    path('api/admin/listeners/', AdminListenerListView.as_view()),
    path('api/admin/listeners', AdminListenerListView.as_view()),
    path('admin/listeners/', AdminListenerListView.as_view()),
    path('admin/listeners', AdminListenerListView.as_view()),
    path('api/admin/listeners/create/', AdminCreateListenerView.as_view()),
    path('api/admin/listeners/create', AdminCreateListenerView.as_view()),
    path('admin/listeners/create/', AdminCreateListenerView.as_view()),
    path('admin/listeners/create', AdminCreateListenerView.as_view()),
    path('api/admin/listeners/delete/', AdminDeleteListenerView.as_view()),
    path('api/admin/listeners/delete', AdminDeleteListenerView.as_view()),
    path('admin/listeners/delete/', AdminDeleteListenerView.as_view()),
    path('admin/listeners/delete', AdminDeleteListenerView.as_view()),
    path('api/admin/listeners/delete/<str:identifier>/', AdminDeleteListenerView.as_view()),
    path('api/admin/listeners/delete/<str:identifier>', AdminDeleteListenerView.as_view()),
    path('admin/listeners/delete/<str:identifier>/', AdminDeleteListenerView.as_view()),
    path('admin/listeners/delete/<str:identifier>', AdminDeleteListenerView.as_view()),
    path('api/admin/listeners/<str:identifier>/', ListenerDetailView.as_view()),
    path('api/admin/listeners/<str:identifier>', ListenerDetailView.as_view()),
    path('admin/listeners/<str:identifier>/', ListenerDetailView.as_view()),
    path('admin/listeners/<str:identifier>', ListenerDetailView.as_view()),


    # Direct Caller Login endpoints (handles all URL variations)
    path('api/auth/caller/login/', CallerLoginView.as_view(), name='api-auth-caller-login'),
    path('api/auth/caller/login', CallerLoginView.as_view()),
    path('auth/caller/login/', CallerLoginView.as_view()),
    path('auth/caller/login', CallerLoginView.as_view()),
    path('api/caller/login/', CallerLoginView.as_view()),
    path('api/caller/login', CallerLoginView.as_view()),
    path('caller/login/', CallerLoginView.as_view()),
    path('caller/login', CallerLoginView.as_view()),
    path('api/api/auth/caller/login/', CallerLoginView.as_view()),
    path('api/api/auth/caller/login', CallerLoginView.as_view()),
    path('api/api/caller/login/', CallerLoginView.as_view()),
    path('api/api/caller/login', CallerLoginView.as_view()),

    # Direct Listener & General Login endpoints (handles all URL variations)
    path('api/auth/listener/login/', ListenerLoginView.as_view(), name='api-auth-listener-login'),
    path('api/auth/listener/login', ListenerLoginView.as_view()),
    path('auth/listener/login/', ListenerLoginView.as_view()),
    path('auth/listener/login', ListenerLoginView.as_view()),
    path('api/listener/login/', ListenerLoginView.as_view()),
    path('api/listener/login', ListenerLoginView.as_view()),
    path('listener/login/', ListenerLoginView.as_view()),
    path('listener/login', ListenerLoginView.as_view()),

    # General login aliases
    path('api/auth/login/', ListenerLoginView.as_view()),
    path('api/auth/login', ListenerLoginView.as_view()),
    path('auth/login/', ListenerLoginView.as_view()),
    path('auth/login', ListenerLoginView.as_view()),
    path('api/login/', ListenerLoginView.as_view()),
    path('api/login', ListenerLoginView.as_view()),
    path('login/', ListenerLoginView.as_view()),
    path('login', ListenerLoginView.as_view()),

    # Caller logout aliases
    path('api/auth/caller/logout/', CallerLogoutView.as_view(), name='api-auth-caller-logout'),
    path('api/auth/caller/logout', CallerLogoutView.as_view()),
    path('auth/caller/logout/', CallerLogoutView.as_view()),
    path('auth/caller/logout', CallerLogoutView.as_view()),
    path('api/caller/logout/', CallerLogoutView.as_view()),
    path('api/caller/logout', CallerLogoutView.as_view()),
    path('caller/logout/', CallerLogoutView.as_view()),
    path('caller/logout', CallerLogoutView.as_view()),

    # Listener logout aliases
    path('api/auth/listener/logout/', ListenerLogoutView.as_view(), name='api-auth-listener-logout'),
    path('api/auth/listener/logout', ListenerLogoutView.as_view()),
    path('auth/listener/logout/', ListenerLogoutView.as_view()),
    path('auth/listener/logout', ListenerLogoutView.as_view()),
    path('api/listener/logout/', ListenerLogoutView.as_view()),
    path('api/listener/logout', ListenerLogoutView.as_view()),
    path('listener/logout/', ListenerLogoutView.as_view()),
    path('listener/logout', ListenerLogoutView.as_view()),
    path('api/listenerlogout/', ListenerLogoutView.as_view(), name='api-listenerlogout'),
    path('api/listenerlogout', ListenerLogoutView.as_view()),
    path('listenerlogout/', ListenerLogoutView.as_view()),
    path('listenerlogout', ListenerLogoutView.as_view()),
    path('api/listener-logout/', ListenerLogoutView.as_view()),
    path('api/listener-logout', ListenerLogoutView.as_view()),
    path('listener-logout/', ListenerLogoutView.as_view()),
    path('listener-logout', ListenerLogoutView.as_view()),
    path('api/api/listener/logout/', ListenerLogoutView.as_view()),
    path('api/api/listener/logout', ListenerLogoutView.as_view()),
    path('api/api/listenerlogout/', ListenerLogoutView.as_view()),
    path('api/api/listenerlogout', ListenerLogoutView.as_view()),

    # General logout aliases
    path('api/auth/logout/', LogoutView.as_view(), name='api-auth-logout'),
    path('api/auth/logout', LogoutView.as_view()),
    path('auth/logout/', LogoutView.as_view()),
    path('auth/logout', LogoutView.as_view()),
    path('api/logout/', LogoutView.as_view()),
    path('api/logout', LogoutView.as_view()),
    path('logout/', LogoutView.as_view()),
    path('logout', LogoutView.as_view()),

    # General delete account aliases
    path('api/auth/delete-account/', DeleteAccountView.as_view(), name='api-auth-delete-account'),
    path('api/auth/delete-account', DeleteAccountView.as_view()),
    path('auth/delete-account/', DeleteAccountView.as_view()),
    path('auth/delete-account', DeleteAccountView.as_view()),
    path('api/delete-account/', DeleteAccountView.as_view()),
    path('api/delete-account', DeleteAccountView.as_view()),
    path('delete-account/', DeleteAccountView.as_view()),
    path('delete-account', DeleteAccountView.as_view()),
    path('api/profile/delete/', DeleteAccountView.as_view()),
    path('api/profile/delete', DeleteAccountView.as_view()),
    path('profile/delete/', DeleteAccountView.as_view()),
    path('profile/delete', DeleteAccountView.as_view()),

    # ==========================================
    # LEGAL & HELPLINE ROUTES
    # ==========================================
    path('api/helpline/', HelplineView.as_view(), name='api-helpline'),
    path('api/helpline', HelplineView.as_view()),
    path('api/api/helpline/', HelplineView.as_view()),
    path('api/api/helpline', HelplineView.as_view()),
    path('helpline/', HelplineView.as_view()),
    path('helpline', HelplineView.as_view()),
    path('api/support/', HelplineView.as_view()),
    path('api/support', HelplineView.as_view()),
    path('support/', HelplineView.as_view()),
    path('support', HelplineView.as_view()),

    path('api/terms-and-conditions/', TermsAndConditionsView.as_view(), name='api-terms-and-conditions'),
    path('api/terms-and-conditions', TermsAndConditionsView.as_view()),
    path('api/api/terms-and-conditions/', TermsAndConditionsView.as_view()),
    path('api/api/terms-and-conditions', TermsAndConditionsView.as_view()),
    path('terms-and-conditions/', TermsAndConditionsView.as_view()),
    path('terms-and-conditions', TermsAndConditionsView.as_view()),
    path('api/terms/', TermsAndConditionsView.as_view()),
    path('api/terms', TermsAndConditionsView.as_view()),
    path('terms/', TermsAndConditionsView.as_view()),
    path('terms', TermsAndConditionsView.as_view()),

    path('api/privacy/', CallerPrivacySettingsView.as_view(), name='api-privacy'),
    path('api/privacy', CallerPrivacySettingsView.as_view()),
    path('privacy/', CallerPrivacySettingsView.as_view()),
    path('privacy', CallerPrivacySettingsView.as_view()),
    path('api/api/privacy/', CallerPrivacySettingsView.as_view()),
    path('api/api/privacy', CallerPrivacySettingsView.as_view()),
    path('api/privacy-policy/', CallerPrivacySettingsView.as_view(), name='api-privacy-policy'),
    path('api/privacy-policy', CallerPrivacySettingsView.as_view()),
    path('api/api/privacy-policy/', CallerPrivacySettingsView.as_view()),
    path('api/api/privacy-policy', CallerPrivacySettingsView.as_view()),
    path('privacy-policy/', CallerPrivacySettingsView.as_view()),
    path('privacy-policy', CallerPrivacySettingsView.as_view()),

    # ==========================================
    # CALLER PROFILE ROUTES (ALL VARIATIONS)
    # ==========================================
    path('api/profile/', ProfileView.as_view(), name='api-profile'),
    path('api/profile', ProfileView.as_view()),
    path('api/profile/<str:identifier>/', ProfileView.as_view()),
    path('api/profile/<str:identifier>', ProfileView.as_view()),
    path('profile/', ProfileView.as_view()),
    path('profile', ProfileView.as_view()),
    path('profile/<str:identifier>/', ProfileView.as_view()),
    path('profile/<str:identifier>', ProfileView.as_view()),

    path('api/caller/profile/', CallerProfileView.as_view(), name='api-caller-profile'),
    path('api/caller/profile', CallerProfileView.as_view()),
    path('api/caller/profile/<str:identifier>/', ProfileView.as_view()),
    path('api/caller/profile/<str:identifier>', ProfileView.as_view()),
    path('caller/profile/', CallerProfileView.as_view()),
    path('caller/profile', CallerProfileView.as_view()),
    path('caller/profile/<str:identifier>/', ProfileView.as_view()),
    path('caller/profile/<str:identifier>', ProfileView.as_view()),

    # My Account: Wallet & Coins endpoints
    path('api/wallet/', WalletView.as_view(), name='api-wallet'),
    path('api/wallet', WalletView.as_view()),
    path('wallet/', WalletView.as_view()),
    path('wallet', WalletView.as_view()),
    path('api/wallet/coins/', GetCoinsView.as_view()),
    path('api/wallet/coins', GetCoinsView.as_view()),
    path('wallet/coins/', GetCoinsView.as_view()),
    path('wallet/coins', GetCoinsView.as_view()),

    # Get Coins endpoints
    path('api/coins/', GetCoinsView.as_view(), name='api-coins'),
    path('api/coins', GetCoinsView.as_view()),
    path('coins/', GetCoinsView.as_view()),
    path('coins', GetCoinsView.as_view()),
    path('api/get-coins/', GetCoinsView.as_view()),
    path('api/get-coins', GetCoinsView.as_view()),
    path('get-coins/', GetCoinsView.as_view()),
    path('get-coins', GetCoinsView.as_view()),
    path('api/getcoins/', GetCoinsView.as_view()),
    path('api/getcoins', GetCoinsView.as_view()),
    path('getcoins/', GetCoinsView.as_view()),
    path('getcoins', GetCoinsView.as_view()),

    # Add Coins endpoints
    path('api/coins/add/', AddCoinsView.as_view(), name='api-coins-add'),
    path('api/coins/add', AddCoinsView.as_view()),
    path('coins/add/', AddCoinsView.as_view()),
    path('coins/add', AddCoinsView.as_view()),
    path('api/add-coins/', AddCoinsView.as_view()),
    path('api/add-coins', AddCoinsView.as_view()),
    path('add-coins/', AddCoinsView.as_view()),
    path('add-coins', AddCoinsView.as_view()),
    path('api/addcoins/', AddCoinsView.as_view()),
    path('api/addcoins', AddCoinsView.as_view()),
    path('addcoins/', AddCoinsView.as_view()),
    path('addcoins', AddCoinsView.as_view()),

    # Coin Purchase & Transaction History
    path('api/coins/history/', CoinPurchaseHistoryView.as_view(), name='api-coin-purchase-history'),
    path('api/coins/history', CoinPurchaseHistoryView.as_view()),
    path('coins/history/', CoinPurchaseHistoryView.as_view()),
    path('coins/history', CoinPurchaseHistoryView.as_view()),
    path('api/coins/purchase-history/', CoinPurchaseHistoryView.as_view(), name='api-coin-purchase-history-alias'),
    path('api/coins/purchase-history', CoinPurchaseHistoryView.as_view()),
    path('coins/purchase-history/', CoinPurchaseHistoryView.as_view()),
    path('coins/purchase-history', CoinPurchaseHistoryView.as_view()),
    path('api/coins/purchases/', CoinPurchaseHistoryView.as_view(), name='api-coin-purchases'),
    path('api/coins/purchases', CoinPurchaseHistoryView.as_view()),
    path('coins/purchases/', CoinPurchaseHistoryView.as_view()),
    path('coins/purchases', CoinPurchaseHistoryView.as_view()),
    path('api/coins/purchase/', CoinPurchaseHistoryView.as_view(), name='api-coin-purchase'),
    path('api/coins/purchase', CoinPurchaseHistoryView.as_view()),
    path('coins/purchase/', CoinPurchaseHistoryView.as_view()),
    path('coins/purchase', CoinPurchaseHistoryView.as_view()),
    path('api/wallet/history/', CoinPurchaseHistoryView.as_view(), name='api-wallet-history'),
    path('api/wallet/history', CoinPurchaseHistoryView.as_view()),
    path('wallet/history/', CoinPurchaseHistoryView.as_view()),
    path('wallet/history', CoinPurchaseHistoryView.as_view()),
    path('api/wallet/transactions/', CoinPurchaseHistoryView.as_view(), name='api-wallet-transactions'),
    path('api/wallet/transactions', CoinPurchaseHistoryView.as_view()),
    path('wallet/transactions/', CoinPurchaseHistoryView.as_view()),
    path('wallet/transactions', CoinPurchaseHistoryView.as_view()),
    path('api/api/coins/history/', CoinPurchaseHistoryView.as_view()),
    path('api/api/coins/history', CoinPurchaseHistoryView.as_view()),
    path('api/api/coins/purchase-history/', CoinPurchaseHistoryView.as_view()),
    path('api/api/coins/purchase-history', CoinPurchaseHistoryView.as_view()),

    # Double-prefix safety for coins
    path('api/api/coins/', GetCoinsView.as_view()),
    path('api/api/coins', GetCoinsView.as_view()),
    path('api/api/coins/add/', AddCoinsView.as_view()),
    path('api/api/coins/add', AddCoinsView.as_view()),
    path('api/api/add-coins/', AddCoinsView.as_view()),
    path('api/api/add-coins', AddCoinsView.as_view()),
    path('api/api/addcoins/', AddCoinsView.as_view()),
    path('api/api/addcoins', AddCoinsView.as_view()),
    path('api/api/get-coins/', GetCoinsView.as_view()),
    path('api/api/get-coins', GetCoinsView.as_view()),
    path('api/api/getcoins/', GetCoinsView.as_view()),
    path('api/api/getcoins', GetCoinsView.as_view()),

    # Call Workflow endpoints (Plural & Singular)
    path('api/calls/request/', CallRequestView.as_view(), name='api-call-request'),
    path('api/calls/request', CallRequestView.as_view()),
    path('calls/request/', CallRequestView.as_view()),
    path('calls/request', CallRequestView.as_view()),
    path('api/call/request/', CallRequestView.as_view()),
    path('api/call/request', CallRequestView.as_view()),
    path('call/request/', CallRequestView.as_view()),
    path('call/request', CallRequestView.as_view()),
    path('api/callrequest/', CallRequestView.as_view()),
    path('api/callrequest', CallRequestView.as_view()),
    path('api/call-request/', CallRequestView.as_view()),
    path('api/call-request', CallRequestView.as_view()),

    path('api/calls/incoming/', IncomingCallsView.as_view(), name='api-calls-incoming'),
    path('api/calls/incoming', IncomingCallsView.as_view()),
    path('calls/incoming/', IncomingCallsView.as_view()),
    path('calls/incoming', IncomingCallsView.as_view()),
    path('api/call/incoming/', IncomingCallsView.as_view()),
    path('api/call/incoming', IncomingCallsView.as_view()),
    path('call/incoming/', IncomingCallsView.as_view()),
    path('call/incoming', IncomingCallsView.as_view()),

    path('api/calls/<int:call_id>/accept/', AcceptCallView.as_view(), name='api-call-accept'),
    path('api/calls/<int:call_id>/accept', AcceptCallView.as_view()),
    path('calls/<int:call_id>/accept/', AcceptCallView.as_view()),
    path('calls/<int:call_id>/accept', AcceptCallView.as_view()),
    path('api/call/<int:call_id>/accept/', AcceptCallView.as_view()),
    path('api/call/<int:call_id>/accept', AcceptCallView.as_view()),
    path('call/<int:call_id>/accept/', AcceptCallView.as_view()),
    path('call/<int:call_id>/accept', AcceptCallView.as_view()),

    path('api/calls/<int:call_id>/reject/', RejectCallView.as_view(), name='api-call-reject'),
    path('api/calls/<int:call_id>/reject', RejectCallView.as_view()),
    path('calls/<int:call_id>/reject/', RejectCallView.as_view()),
    path('calls/<int:call_id>/reject', RejectCallView.as_view()),
    path('api/call/<int:call_id>/reject/', RejectCallView.as_view()),
    path('api/call/<int:call_id>/reject', RejectCallView.as_view()),
    path('call/<int:call_id>/reject/', RejectCallView.as_view()),
    path('call/<int:call_id>/reject', RejectCallView.as_view()),

    path('api/calls/<int:call_id>/start/', StartCallView.as_view(), name='api-call-start'),
    path('api/calls/<int:call_id>/start', StartCallView.as_view()),
    path('calls/<int:call_id>/start/', StartCallView.as_view()),
    path('calls/<int:call_id>/start', StartCallView.as_view()),
    path('api/call/<int:call_id>/start/', StartCallView.as_view()),
    path('api/call/<int:call_id>/start', StartCallView.as_view()),
    path('call/<int:call_id>/start/', StartCallView.as_view()),
    path('call/<int:call_id>/start', StartCallView.as_view()),

    path('api/calls/<int:call_id>/end/', EndCallView.as_view(), name='api-call-end'),
    path('api/calls/<int:call_id>/end', EndCallView.as_view()),
    path('calls/<int:call_id>/end/', EndCallView.as_view()),
    path('calls/<int:call_id>/end', EndCallView.as_view()),
    path('api/call/<int:call_id>/end/', EndCallView.as_view()),
    path('api/call/<int:call_id>/end', EndCallView.as_view()),
    path('call/<int:call_id>/end/', EndCallView.as_view()),
    path('call/<int:call_id>/end', EndCallView.as_view()),

    path('api/calls/<int:call_id>/agora-token/', AgoraCallTokenView.as_view(), name='api-call-agora-token'),
    path('api/calls/<int:call_id>/agora-token', AgoraCallTokenView.as_view()),
    path('calls/<int:call_id>/agora-token/', AgoraCallTokenView.as_view()),
    path('calls/<int:call_id>/agora-token', AgoraCallTokenView.as_view()),
    path('api/call/<int:call_id>/agora-token/', AgoraCallTokenView.as_view()),
    path('api/call/<int:call_id>/agora-token', AgoraCallTokenView.as_view()),
    path('call/<int:call_id>/agora-token/', AgoraCallTokenView.as_view()),
    path('call/<int:call_id>/agora-token', AgoraCallTokenView.as_view()),

    # Double-prefix safety for call workflow
    path('api/api/calls/request/', CallRequestView.as_view()),
    path('api/api/calls/request', CallRequestView.as_view()),
    path('api/api/call/request/', CallRequestView.as_view()),
    path('api/api/call/request', CallRequestView.as_view()),
    path('api/api/calls/incoming/', IncomingCallsView.as_view()),
    path('api/api/calls/incoming', IncomingCallsView.as_view()),
    path('api/api/call/incoming/', IncomingCallsView.as_view()),
    path('api/api/call/incoming', IncomingCallsView.as_view()),
    path('api/api/calls/<int:call_id>/accept/', AcceptCallView.as_view()),
    path('api/api/calls/<int:call_id>/accept', AcceptCallView.as_view()),
    path('api/api/call/<int:call_id>/accept/', AcceptCallView.as_view()),
    path('api/api/call/<int:call_id>/accept', AcceptCallView.as_view()),
    path('api/api/calls/<int:call_id>/reject/', RejectCallView.as_view()),
    path('api/api/calls/<int:call_id>/reject', RejectCallView.as_view()),
    path('api/api/call/<int:call_id>/reject/', RejectCallView.as_view()),
    path('api/api/call/<int:call_id>/reject', RejectCallView.as_view()),
    path('api/api/calls/<int:call_id>/start/', StartCallView.as_view()),
    path('api/api/calls/<int:call_id>/start', StartCallView.as_view()),
    path('api/api/call/<int:call_id>/start/', StartCallView.as_view()),
    path('api/api/call/<int:call_id>/start', StartCallView.as_view()),
    path('api/api/calls/<int:call_id>/end/', EndCallView.as_view()),
    path('api/api/calls/<int:call_id>/end', EndCallView.as_view()),
    path('api/api/call/<int:call_id>/end/', EndCallView.as_view()),
    path('api/api/call/<int:call_id>/end', EndCallView.as_view()),
    path('api/api/calls/<int:call_id>/agora-token/', AgoraCallTokenView.as_view()),
    path('api/api/calls/<int:call_id>/agora-token', AgoraCallTokenView.as_view()),
    path('api/api/call/<int:call_id>/agora-token/', AgoraCallTokenView.as_view()),
    path('api/api/call/<int:call_id>/agora-token', AgoraCallTokenView.as_view()),

    # Call History endpoints
    path('api/calls/history/', CallHistoryView.as_view(), name='api-calls-history'),
    path('api/calls/history', CallHistoryView.as_view()),
    path('calls/history/', CallHistoryView.as_view()),
    path('calls/history', CallHistoryView.as_view()),
    path('api/callhistory/', CallHistoryView.as_view(), name='api-call-history'),
    path('api/callhistory', CallHistoryView.as_view()),
    path('callhistory/', CallHistoryView.as_view()),
    path('callhistory', CallHistoryView.as_view()),
    path('api/call-history/', CallHistoryView.as_view()),
    path('api/call-history', CallHistoryView.as_view()),
    path('call-history/', CallHistoryView.as_view()),
    path('call-history', CallHistoryView.as_view()),
    path('api/calls/', CallHistoryView.as_view()),
    path('api/calls', CallHistoryView.as_view()),
    path('calls/', CallHistoryView.as_view()),
    path('calls', CallHistoryView.as_view()),
    path('api/callhistory/<int:call_id>/', CallDetailView.as_view()),
    path('api/callhistory/<int:call_id>', CallDetailView.as_view()),
    path('callhistory/<int:call_id>/', CallDetailView.as_view()),
    path('callhistory/<int:call_id>', CallDetailView.as_view()),
    path('api/call-history/<int:call_id>/', CallDetailView.as_view()),
    path('api/call-history/<int:call_id>', CallDetailView.as_view()),
    path('call-history/<int:call_id>/', CallDetailView.as_view()),
    path('call-history/<int:call_id>', CallDetailView.as_view()),

    # Double-prefix safety for call history
    path('api/api/calls/history/', CallHistoryView.as_view()),
    path('api/api/calls/history', CallHistoryView.as_view()),
    path('api/api/callhistory/', CallHistoryView.as_view()),
    path('api/api/callhistory', CallHistoryView.as_view()),
    path('api/api/call-history/', CallHistoryView.as_view()),
    path('api/api/call-history', CallHistoryView.as_view()),

    path('api/caller/account/', CallerAccountDeleteView.as_view(), name='api-caller-account-delete'),
    path('api/caller/account', CallerAccountDeleteView.as_view()),
    path('caller/account/', CallerAccountDeleteView.as_view()),
    path('caller/account', CallerAccountDeleteView.as_view()),

    # Caller Favorites endpoints
    path('api/favourites/', CallerFavoritesView.as_view(), name='api-caller-favourites'),
    path('api/favourites', CallerFavoritesView.as_view()),
    path('api/favourites/<int:agent_id>/', CallerFavoriteDetailView.as_view(), name='api-caller-favourite-detail'),
    path('api/favourites/<int:agent_id>', CallerFavoriteDetailView.as_view()),
    path('api/favourites/<str:agent_id>/', CallerFavoriteDetailView.as_view()),
    path('api/favourites/<str:agent_id>', CallerFavoriteDetailView.as_view()),
    path('favourites/', CallerFavoritesView.as_view()),
    path('favourites', CallerFavoritesView.as_view()),
    path('favourites/<int:agent_id>/', CallerFavoriteDetailView.as_view()),
    path('favourites/<int:agent_id>', CallerFavoriteDetailView.as_view()),
    path('favourites/<str:agent_id>/', CallerFavoriteDetailView.as_view()),
    path('favourites/<str:agent_id>', CallerFavoriteDetailView.as_view()),

    # American spelling aliases
    path('api/favorites/', CallerFavoritesView.as_view(), name='api-caller-favorites'),
    path('api/favorites', CallerFavoritesView.as_view()),
    path('api/favorites/<int:agent_id>/', CallerFavoriteDetailView.as_view(), name='api-caller-favorite-detail'),
    path('api/favorites/<int:agent_id>', CallerFavoriteDetailView.as_view()),
    path('api/favorites/<str:agent_id>/', CallerFavoriteDetailView.as_view()),
    path('api/favorites/<str:agent_id>', CallerFavoriteDetailView.as_view()),
    path('favorites/', CallerFavoritesView.as_view()),
    path('favorites', CallerFavoritesView.as_view()),
    path('favorites/<int:agent_id>/', CallerFavoriteDetailView.as_view()),
    path('favorites/<int:agent_id>', CallerFavoriteDetailView.as_view()),
    path('favorites/<str:agent_id>/', CallerFavoriteDetailView.as_view()),
    path('favorites/<str:agent_id>', CallerFavoriteDetailView.as_view()),

    # Double-prefix safety
    path('api/api/favourites/', CallerFavoritesView.as_view()),
    path('api/api/favourites', CallerFavoritesView.as_view()),
    path('api/api/favourites/<int:agent_id>/', CallerFavoriteDetailView.as_view()),
    path('api/api/favourites/<int:agent_id>', CallerFavoriteDetailView.as_view()),
    path('api/api/favourites/<str:agent_id>/', CallerFavoriteDetailView.as_view()),
    path('api/api/favourites/<str:agent_id>', CallerFavoriteDetailView.as_view()),
    path('api/api/favorites/', CallerFavoritesView.as_view()),
    path('api/api/favorites', CallerFavoritesView.as_view()),
    path('api/api/favorites/<int:agent_id>/', CallerFavoriteDetailView.as_view()),
    path('api/api/favorites/<int:agent_id>', CallerFavoriteDetailView.as_view()),
    path('api/api/favorites/<str:agent_id>/', CallerFavoriteDetailView.as_view()),
    path('api/api/favorites/<str:agent_id>', CallerFavoriteDetailView.as_view()),

    path('api/callerprofileview/', CallerProfileView.as_view(), name='api-callerprofileview'),
    path('api/callerprofileview', CallerProfileView.as_view()),
    path('api/callerprofileview/<str:identifier>/', CallerProfileView.as_view()),
    path('api/callerprofileview/<str:identifier>', CallerProfileView.as_view()),
    path('callerprofileview/', CallerProfileView.as_view()),
    path('callerprofileview', CallerProfileView.as_view()),
    path('callerprofileview/<str:identifier>/', CallerProfileView.as_view()),
    path('callerprofileview/<str:identifier>', CallerProfileView.as_view()),

    path('api/callerprofile/', CallerProfileView.as_view(), name='api-callerprofile'),
    path('api/callerprofile', CallerProfileView.as_view()),
    path('api/callerprofile/<str:identifier>/', CallerProfileView.as_view()),
    path('api/callerprofile/<str:identifier>', CallerProfileView.as_view()),
    path('callerprofile/', CallerProfileView.as_view()),
    path('callerprofile', CallerProfileView.as_view()),
    path('callerprofile/<str:identifier>/', CallerProfileView.as_view()),
    path('callerprofile/<str:identifier>', CallerProfileView.as_view()),

    path('api/caller-profile/', CallerProfileView.as_view()),
    path('api/caller-profile', CallerProfileView.as_view()),
    path('caller-profile/', CallerProfileView.as_view()),
    path('caller-profile', CallerProfileView.as_view()),

    # Double-prefix safety (for Postman environment baseUrl with /api)
    path('api/api/profile/', ProfileView.as_view()),
    path('api/api/profile', ProfileView.as_view()),
    path('api/api/caller/profile/', CallerProfileView.as_view()),
    path('api/api/caller/profile', CallerProfileView.as_view()),
    path('api/api/wallet/', WalletView.as_view()),
    path('api/api/wallet', WalletView.as_view()),
    path('api/api/caller/account/', CallerAccountDeleteView.as_view()),
    path('api/api/caller/account', CallerAccountDeleteView.as_view()),
    path('api/api/callerprofileview/', CallerProfileView.as_view()),
    path('api/api/callerprofileview', CallerProfileView.as_view()),

    # ==========================================
    # AGENT BACKEND API ROUTES (ALL VARIANTS)
    # ==========================================
    # Agent Authentication
    path('api/auth/agent/login/', AgentLoginView.as_view(), name='api-auth-agent-login'),
    path('api/auth/agent/login', AgentLoginView.as_view()),
    path('auth/agent/login/', AgentLoginView.as_view()),
    path('auth/agent/login', AgentLoginView.as_view()),
    path('api/agent/login/', AgentLoginView.as_view()),
    path('api/agent/login', AgentLoginView.as_view()),
    path('agent/login/', AgentLoginView.as_view()),
    path('agent/login', AgentLoginView.as_view()),
    path('api/api/auth/agent/login/', AgentLoginView.as_view()),
    path('api/api/auth/agent/login', AgentLoginView.as_view()),
    path('api/api/agent/login/', AgentLoginView.as_view()),
    path('api/api/agent/login', AgentLoginView.as_view()),

    # Agent Logout
    path('api/auth/agent/logout/', AgentLogoutView.as_view(), name='api-auth-agent-logout'),
    path('api/auth/agent/logout', AgentLogoutView.as_view()),
    path('auth/agent/logout/', AgentLogoutView.as_view()),
    path('auth/agent/logout', AgentLogoutView.as_view()),
    path('api/agent/logout/', AgentLogoutView.as_view()),
    path('api/agent/logout', AgentLogoutView.as_view()),
    path('agent/logout/', AgentLogoutView.as_view()),
    path('agent/logout', AgentLogoutView.as_view()),
    path('api/api/auth/agent/logout/', AgentLogoutView.as_view()),
    path('api/api/auth/agent/logout', AgentLogoutView.as_view()),

    # Agent Password Reset
    path('api/agent/password/forgot/', AgentForgotPasswordView.as_view(), name='api-agent-password-forgot'),
    path('api/agent/password/forgot', AgentForgotPasswordView.as_view()),
    path('agent/password/forgot/', AgentForgotPasswordView.as_view()),
    path('agent/password/forgot', AgentForgotPasswordView.as_view()),
    path('api/auth/agent/password/forgot/', AgentForgotPasswordView.as_view()),
    path('auth/agent/password/forgot/', AgentForgotPasswordView.as_view()),
    path('api/agent/password/reset/', AgentResetPasswordView.as_view(), name='api-agent-password-reset'),
    path('api/agent/password/reset', AgentResetPasswordView.as_view()),
    path('agent/password/reset/', AgentResetPasswordView.as_view()),
    path('agent/password/reset', AgentResetPasswordView.as_view()),
    path('api/auth/agent/password/reset/', AgentResetPasswordView.as_view()),
    path('auth/agent/password/reset/', AgentResetPasswordView.as_view()),

    # Agent Profile
    path('api/agent/profile/', AgentProfileView.as_view(), name='api-agent-profile'),
    path('api/agent/profile', AgentProfileView.as_view()),
    path('agent/profile/', AgentProfileView.as_view()),
    path('agent/profile', AgentProfileView.as_view()),
    path('api/api/agent/profile/', AgentProfileView.as_view()),
    path('api/api/agent/profile', AgentProfileView.as_view()),

    # Agent Professions / Categories
    path('api/agent/professions/', AgentProfessionsView.as_view(), name='api-agent-professions'),
    path('api/agent/professions', AgentProfessionsView.as_view()),
    path('agent/professions/', AgentProfessionsView.as_view()),
    path('agent/professions', AgentProfessionsView.as_view()),

    # Agent Rate
    path('api/agent/rate/', AgentRateView.as_view(), name='api-agent-rate'),
    path('api/agent/rate', AgentRateView.as_view()),
    path('agent/rate/', AgentRateView.as_view()),
    path('agent/rate', AgentRateView.as_view()),

    # Agent Duty
    path('api/agent/duty/', AgentDutyView.as_view(), name='api-agent-duty'),
    path('api/agent/duty', AgentDutyView.as_view()),
    path('agent/duty/', AgentDutyView.as_view()),
    path('agent/duty', AgentDutyView.as_view()),
    path('api/agent/duty/on/', AgentDutyOnView.as_view(), name='api-agent-duty-on'),
    path('api/agent/duty/on', AgentDutyOnView.as_view()),
    path('agent/duty/on/', AgentDutyOnView.as_view()),
    path('agent/duty/on', AgentDutyOnView.as_view()),
    path('api/agent/duty/off/', AgentDutyOffView.as_view(), name='api-agent-duty-off'),
    path('api/agent/duty/off', AgentDutyOffView.as_view()),
    path('agent/duty/off/', AgentDutyOffView.as_view()),
    path('agent/duty/off', AgentDutyOffView.as_view()),

    # Agent Dashboard
    path('api/agent/dashboard/', AgentDashboardView.as_view(), name='api-agent-dashboard'),
    path('api/agent/dashboard', AgentDashboardView.as_view()),
    path('agent/dashboard/', AgentDashboardView.as_view()),
    path('agent/dashboard', AgentDashboardView.as_view()),
    path('api/api/agent/dashboard/', AgentDashboardView.as_view()),
    path('api/api/agent/dashboard', AgentDashboardView.as_view()),

    # Agent Earnings
    path('api/agent/earnings/today/', AgentEarningsTodayView.as_view(), name='api-agent-earnings-today'),
    path('api/agent/earnings/today', AgentEarningsTodayView.as_view()),
    path('agent/earnings/today/', AgentEarningsTodayView.as_view()),
    path('agent/earnings/today', AgentEarningsTodayView.as_view()),
    path('api/agent/earnings/', AgentEarningsHistoryView.as_view(), name='api-agent-earnings-history'),
    path('api/agent/earnings', AgentEarningsHistoryView.as_view()),
    path('agent/earnings/', AgentEarningsHistoryView.as_view()),
    path('agent/earnings', AgentEarningsHistoryView.as_view()),

    # Agent Wallet & Payouts
    path('api/agent/wallet/', AgentWalletView.as_view(), name='api-agent-wallet'),
    path('api/agent/wallet', AgentWalletView.as_view()),
    path('agent/wallet/', AgentWalletView.as_view()),
    path('agent/wallet', AgentWalletView.as_view()),
    path('api/agent/payouts/', AgentPayoutView.as_view(), name='api-agent-payouts'),
    path('api/agent/payouts', AgentPayoutView.as_view()),
    path('agent/payouts/', AgentPayoutView.as_view()),
    path('agent/payouts', AgentPayoutView.as_view()),

    # Agent Ratings & Recent Sessions
    path('api/agent/rating/', AgentRatingView.as_view(), name='api-agent-rating'),
    path('api/agent/rating', AgentRatingView.as_view()),
    path('agent/rating/', AgentRatingView.as_view()),
    path('agent/rating', AgentRatingView.as_view()),
    path('api/agent/reviews/', AgentRatingView.as_view(), name='api-agent-reviews'),
    path('api/agent/reviews', AgentRatingView.as_view()),
    path('agent/reviews/', AgentRatingView.as_view()),
    path('agent/reviews', AgentRatingView.as_view()),
    path('api/agent/sessions/recent/', AgentRecentSessionsView.as_view(), name='api-agent-sessions-recent'),
    path('api/agent/sessions/recent', AgentRecentSessionsView.as_view()),
    path('agent/sessions/recent/', AgentRecentSessionsView.as_view()),
    path('agent/sessions/recent', AgentRecentSessionsView.as_view()),

    # Standard App routing
    path('api/api/', include('core.urls')),
    path('api/', include('core.urls')),
    path('', include('core.urls')),
]


# Serve user-uploaded media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

